language: cpp

compiler: gcc

sudo: required

install: sudo apt-get install software-properties-common &&
         sudo add-apt-repository ppa:george-edison55/cmake-3.x -y &&
         sudo apt-get update &&
         sudo apt-get install cmake -y &&
         sudo apt-get upgrade -y

script: ./build.sh && ./test.sh

notifications:
  email:
    - xf1280@gmail.com
    - govinda.kamath@gmail.com
    - ilanshom@gmail.com
